"""growth_references_and_zscores

Revision ID: 4709a5b6f82d
Revises: e602a2057552
Create Date: 2026-06-12 16:15:07.616833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4709a5b6f82d'
down_revision: Union[str, Sequence[str], None] = 'e602a2057552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('growth_ref_head_age',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('age_months', sa.Float(), nullable=False),
    sa.Column('L', sa.Float(), nullable=False),
    sa.Column('M', sa.Float(), nullable=False),
    sa.Column('S', sa.Float(), nullable=False),
    sa.Column('percentiles', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_growth_ref_head_age_sex'), 'growth_ref_head_age', ['sex'], unique=False)
    op.create_table('growth_ref_length_age',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('age_months', sa.Float(), nullable=False),
    sa.Column('L', sa.Float(), nullable=False),
    sa.Column('M', sa.Float(), nullable=False),
    sa.Column('S', sa.Float(), nullable=False),
    sa.Column('percentiles', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_growth_ref_length_age_sex'), 'growth_ref_length_age', ['sex'], unique=False)
    op.create_table('growth_ref_weight_age',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('age_months', sa.Float(), nullable=False),
    sa.Column('L', sa.Float(), nullable=False),
    sa.Column('M', sa.Float(), nullable=False),
    sa.Column('S', sa.Float(), nullable=False),
    sa.Column('percentiles', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_growth_ref_weight_age_sex'), 'growth_ref_weight_age', ['sex'], unique=False)
    op.create_table('growth_ref_weight_length',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('length_cm', sa.Float(), nullable=False),
    sa.Column('L', sa.Float(), nullable=False),
    sa.Column('M', sa.Float(), nullable=False),
    sa.Column('S', sa.Float(), nullable=False),
    sa.Column('percentiles', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_growth_ref_weight_length_sex'), 'growth_ref_weight_length', ['sex'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('child_id', sa.String(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('active', sa.Enum('active', 'resolved', name='alert_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['growth_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_child_id'), 'alerts', ['child_id'], unique=False)
    op.add_column('growth_records', sa.Column('head_circumference', sa.Float(), nullable=True))
    op.add_column('growth_records', sa.Column('weight_zscore', sa.Float(), nullable=True))
    op.add_column('growth_records', sa.Column('height_zscore', sa.Float(), nullable=True))
    op.add_column('growth_records', sa.Column('head_zscore', sa.Float(), nullable=True))
    op.add_column('growth_records', sa.Column('weight_percentile', sa.Float(), nullable=True))
    op.add_column('growth_records', sa.Column('height_percentile', sa.Float(), nullable=True))
    op.add_column('growth_records', sa.Column('head_percentile', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('growth_records', 'head_percentile')
    op.drop_column('growth_records', 'height_percentile')
    op.drop_column('growth_records', 'weight_percentile')
    op.drop_column('growth_records', 'head_zscore')
    op.drop_column('growth_records', 'height_zscore')
    op.drop_column('growth_records', 'weight_zscore')
    op.drop_column('growth_records', 'head_circumference')
    op.drop_index(op.f('ix_alerts_child_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_growth_ref_weight_length_sex'), table_name='growth_ref_weight_length')
    op.drop_table('growth_ref_weight_length')
    op.drop_index(op.f('ix_growth_ref_weight_age_sex'), table_name='growth_ref_weight_age')
    op.drop_table('growth_ref_weight_age')
    op.drop_index(op.f('ix_growth_ref_length_age_sex'), table_name='growth_ref_length_age')
    op.drop_table('growth_ref_length_age')
    op.drop_index(op.f('ix_growth_ref_head_age_sex'), table_name='growth_ref_head_age')
    op.drop_table('growth_ref_head_age')
    # ### end Alembic commands ###
